### ISSUE TITLE
[FEATURE REQUEST]: 

### ISSUE THREAD

**Issue by WataLaker37821** [spartacus04/jext-reborn#152]
### Is your feature request related to a problem? Please describe.

Can you please add a lang file, so anyone could translate any buttons or texts in future? cos the word: jukebox is translated in russian as: Igor (Игорь) and thats totally wrong, Игорь means name, not a music player, right translation is: Проигрыватель

### Describe the solution you'd like.

Adding a language file

**Comment by spartacus04** [comment]
Hi, you can help translate the plugin into other languages [here](https://crowdin.com/project/jext-reborn). The translation is probably wrong because I used an auto translator for some languages. As for the language file you can either set the translation to "auto" which uses the languages from crowdin, or "custom" which creates a custom language file that is applied to each player.

**Comment by WataLaker37821** [comment]
Okay, i made some changes on crowdin yesterday, so i think its okay now

четверг, 3 августа 2023 г. пользователь Andrew ***@***.***>
написал:

**Comment by spartacus04** [comment]
Yeah i just merged them in the plugin. When I fix the other bug you submitted I'll publish them
