### ISSUE TITLE
 Can players be allowed to teleport to their friends who are currently playing music and hear the progress of the music that is already playing?

### ISSUE THREAD

**Issue by 347180440** [spartacus04/jext-reborn#155]
### Is your feature request related to a problem? Please describe.

Current Issues:
Players can only hear the sound when they are near the jukebox and if they play music. Players who teleport in the middle of the music being played cannot hear the music that is currently playing.
Newly joined players also cannot hear the music being played on jukeboxes, which might be an unresolved issue.

### Describe the solution you'd like.

Players, as long as they play music near the jukebox, can still hear the music when they teleport away and return. Can you make it so that when a player uses the jukebox to play music, it is transmitted to all players on the server, even if the other players cannot hear it, but when they teleport in the middle of the music, they can hear the progress of the music?

**Comment by spartacus04** [comment]
Hi, thanks for the feature request,
after doing a bit of research I figured out how to play music to all players in the world in a certain location.
Basically minecraft when playing music in a certain location checks if the player is nearby and if it isn't the music won't play.
I bypassed this by playing the music to each player manually at a specified location.

However since music can only be played to a player in the same world as the source players coming from other dimensions and joining the server won't have the music played.

**Comment by 347180440** [comment]
In version 1.2.6, the same music cannot be played simultaneously in separate worlds.

**Comment by spartacus04** [comment]
you mean from the same jukebox? or from different jukeboxes in different worlds?

**Comment by 347180440** [comment]
In the same world, different distant chunks cannot play the same music.

**Comment by 347180440** [comment]
The idea is that in the main world, if player 1 is playing a song and player 2 starts playing the same song from a different location, player 1's playback will stop.

**Comment by 347180440** [comment]
In the main world, if player 1 is playing a song and player 2 starts playing the same song from a different location, the playback on player 1's side will stop.

**Comment by spartacus04** [comment]
Do you have the allow music overlap option enabled in the config?

**Comment by 347180440** [comment]
Resolved it! Turns out configuring it required a server restart as well.
